sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
jdk:
  - oraclejdk6
  - oraclejdk7
  - openjdk7
script:
  - mvn -U clean install -Dall -Djava.awt.headless=true -DskipTests=false
notifications:
  email: false
  on_failure: never
env: GDAL_LIBRARY_NAME=disabled_see_geot-4733
